name: Security Vulnerability
description: Report a security issue (will be handled privately)
labels: ["security"]
body:
  - type: markdown
    attributes:
      value: |
        **⚠️ Security reports are public by default in GitHub Issues.**
        
        For sensitive security issues, consider using private reporting methods if available, or email the maintainers directly.

  - type: textarea
    id: vulnerability-description
    attributes:
      label: Vulnerability description
      description: Describe the security issue you've found
      placeholder: "Found a potential security issue with..."
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential impact
      description: What could an attacker do with this vulnerability?
      placeholder: "This could allow an attacker to..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: How can this vulnerability be reproduced? (Be careful not to include exploit code)
      placeholder: "1. Navigate to... 2. Submit payload... 3. Observe..."
    validations:
      required: false